### ISSUE TITLE
Merc Bomb laser bug

### ISSUE THREAD

**Issue by duralakun** [yavl/teeworlds-infclassR#10]
Sometimes when merc heart bombs explode they will cause lasers to go straight in direction of the left top corner over a great distance.
I am not sure if this is only visual or has an effect.

**Comment by duralakun** [comment]
I did some debugging on this issue and found out that this would happen often in infc_hardcorepit (a very small map). I then discovered that the StartPoint of the Laser will be (0,0).
I then wrote a dirty fix for it, which just checks if the StartPoint is (0,0), this works, we can use it until someone finds out how to fix this bug. I will commit this bug fix later.

**Comment by duralakun** [comment]
I did more research, i think there is a break missing here:
https://github.com/yavl/teeworlds-infclassR/blob/master/src/game/server/entities/growingexplosion.cpp#L171
if there is no break on purpose, than i think this might also need to be initialized:
https://github.com/yavl/teeworlds-infclassR/blob/master/src/game/server/entities/growingexplosion.cpp#L82

**Comment by bretonium** [comment]
I think this bug can be closed when we merge #45

**Comment by bretonium** [comment]
#45 is merged, closing this bug
