### ISSUE TITLE
Introduce IntervalTick() for non-real-time updates

### ISSUE THREAD

**Issue by teoman002** [yavl/teeworlds-infclassR#106]
**Problem:**
- Often `GetActivePlayerCount()` in server.cpp is called from different locations. The number has to be generated all again instead of generating it once all x seconds and storing the value into an instance variable, that can be accessed from different locations.
- Sometimes `FindFirst(CGameWorld::ENTTYPE_CHARACTER)` has not to be called in Tick() in real-time. hero-flag.cpp for example can check for players all 0.3 seconds, which is still enough time to receive it without lag.
- Turrets do not need real-time player detection (radar), 0.5 seconds are enough to check if a player is in range.
- To conclude: the amount of entity calls can sometimes reduced

**Proposed solution:**
- virtual function Intervalltick() in base class which can be implemented by each child class.
- It has an interval timer and does non-real-time updates in a specific object e.g. turret.cpp

**Comment by duralakun** [comment]
> Often `GetActivePlayerCount()` in server.cpp is called from different locations. The number has to be generated all again instead of generating it once all x seconds and storing the value into an instance variable, that can be accessed from different locations.
It should be possible to create a global variable "ActivePlayerCount" then change this variable whenever a a player leaves/joins/switches to spectator. This way we never to to loop to find out how many players there are.
So if we do this, i would suggest making these variable:
- ActivePlayerNum
- PlayerSpectatingNum
The names can be different. Question is only where to make this vars? And where to change them?

**Comment by teoman002** [comment]
**Todo:**
- Zombie counter
- Human counter
- player counter
- remove GetActivePlayer from server.cpp

**remove special PlayerIterator instances**
- https://github.com/yavl/teeworlds-infclassR/blob/master/src/game/server/entities/hero-flag.cpp#L111
- https://github.com/yavl/teeworlds-infclassR/blob/master/src/game/server/gamecontext.cpp#L4301
- https://github.com/yavl/teeworlds-infclassR/blob/master/src/game/server/gamecontroller.cpp#L515


**add to gamecontext:**
- GetNumberZombies()
- GetNumberHumans()
- GetActivePlayers()
- GetNumberSpectators()
- m_NbZombies
- m_NbHumans
- m_NbActivePlayers
- m_NbSpectators



**OnclientEnter()**
```
if (player joined)
    if (player active)
          m_NbActivePlayers ++
    if (player spectator)
         m_NbSpectators ++
```

**Comment by teoman002** [comment]
Server is fast enough. No intervallTick needed.
