### ISSUE TITLE
Boomer radius too big, smoker damage too strong

### ISSUE THREAD

**Issue by teoman002** [yavl/teeworlds-infclassR#120]

**Comment by ResamVi** [comment]
By "boomer radius too big" do you mean the radius that is currently set on breton's server? Because it actually is smaller than what is default

**Comment by teoman002** [comment]
I wondered that in warehouse2 the boomer could kill me through 2 tile walls. But maybe that was map specific.

**Comment by bretonium** [comment]
> I wondered that in warehouse2 the boomer could kill me through 2 tile walls. But maybe that was map specific.

That is correct. With infclass from this repo, boomer can boom through 3 tiles. On my server, boomer booms through ~2 tiles.

> Smoker damage too strong:
> I've gone ahead and tested this ingame: A fully armored human survives a smoker hook for 7 damage ticks or 3 seconds. The zombie has to re-apply his hook atleast once or this won't work.

I encourage you to test it on infclass1 servers and remember how it was on Stitch626 servers. It is 2/s there. In this repo it is 3/s.
