### ISSUE TITLE
turret disappears if a target dies

### ISSUE THREAD

**Issue by bretonium** [yavl/teeworlds-infclassR#123]
I don't have the exact steps to reproduce, but maybe it still can help.

1. In 3+-people game take hero and find flag or many flags
2. Place turrets
3. Turrets should become ready to fire
4. Wait for a zombie to come up close
5. (Not sure what the exact step here, so here are 2 options)
    - Kill the zombie while the turret is ready and has not fired
    - Kill the zombie while plasma from the turret is flying, but has not hit the zombie yet

Expected: plasma clot either flies till it hits the ground, disappears or re-targets on another zombie, turret stays as is
Observed: turret disappears together with all its plasma clots

**Comment by teoman002** [comment]
current behaviour of turrets:
- Reset() is called when lifespan < 0
- Reset() is called when ownerchar does not exist.
- Reset() is called when owner dies by CCharacter::DestroyChildEntities()
- Reset() is called when zombies runs into turret, this might be buggy -> Testing.
- Reset() is called when owner dies and plasma is deleted, this is an error.

future fixed behaviour of turrets:
- Reset() is called when lifespan < 0
- Reset() is called when owner dies by CCharacter::DestroyChildEntities()
- Reset() is called when zombies runs into turret.
- Plasma have their own ENTTYPE and do not use the one of laser.

**Comment by teoman002** [comment]
@bretonium can you observer that further? There is no option in the program code that leads to turrets destruction if zombies die.
It is a feature that zombies can destroy turrets by running into them.
If a plasma looses its target, it will destroy itself without retargeting.
