### ISSUE TITLE
geolite2 not available - compile on a x86 machine

### ISSUE THREAD

**Issue by teoman002** [yavl/teeworlds-infclassR#124]
I want to compile InfC on a x86 machine, but I can't find an appropriate geolite2++ package.

This is not compatible:
geolite2++-0.0.1-2561-amd-64.deb

Is there an option to ignore geolite2++ or is InfC x64 only?

**Comment by yavl** [comment]
When you run bam, you have to set nogeolocation argument to false
```
bam server_debug nogeolocation=false
```
