### ISSUE TITLE
Helping.

### ISSUE THREAD

**Issue by Risetw** [yavl/teeworlds-infclassR#125]
I try to help, **@teoman002** is helping me.

**Comment by teoman002** [comment]
I know we are not at this point yet but here are some rules for helping.

**Rules for working together:**
- Use branches for your features
- Use pull requests to ask other people to review your code that is included in a branch
- Compile and test your code (for crashes) before you upload.
- Don't push your changes directly into master unless you do a small bugfix.
- I created a master_dev branch, if features are semi stable, we can merge your feature into it.
- Don't rebase your branches if some commits are already uploaded on the server AND if it is likely that someone is working with it. 
- If you think nobody has yet worked with it, correct the server branch with `git push --force origin feature_123`
- You can rebase local changes as much as you like.

**On how to use git:**
- Before coding anything do a `git pull`
- If you coded something but forget to download changes on server first, do a `git pull -r`
- No you want to create a feature, create your own branch:  `git checkout -b feature_123`
- Code something
- Add the changes to the index: `git add src/*`
- If you want to de-index files: `git reset fileName`
- If a file was changed accidentally, do a local reset: `git checkout -- fileName`
- Commit the changes locally with message: `git commit -m "Added feature_123"`
- optional: do some other changes, and add, commit them.
- Upload the changes to the github server `git push origin feature_123`
- If a upstream error appears, read the warning and do what is instructed there.

**Comment by teoman002** [comment]
When I have some free time on my hands, I will write a tutorial on how to add the whiteHole entity into the game.

**Comment by teoman002** [comment]
Please have a look at our new wiki pages:

[Git introduction](https://github.com/yavl/teeworlds-infclassR/wiki/How-to-work-together-on-github)
[How to add a weapon](https://github.com/yavl/teeworlds-infclassR/wiki/How-to-add-a-weapon-to-InfClass)
