### ISSUE TITLE
Initial infection is out of order

### ISSUE THREAD

**Issue by bretonium** [yavl/teeworlds-infclassR#126]
Steps to reproduce:

1. Join a server
2. Wait till more people join
3. Join as spectator and wait for rounds to switch

Expected: initial infected are chosen in order
Observed: after some time, almost always one person gets selected to become initial zombie

This is not reproducible on oi8306. This is reproducible on test oi8306 or any other server based on current `master`.

**Comment by teoman002** [comment]
Can you elaborate on what seems incorrect? I don't understand the issue.

If people leave the game and rejoin the game from spectators, they will be zombie next round. 
Nothing wrong with that.

**Comment by bretonium** [comment]
> Can you elaborate on what seems incorrect? I don't understand the issue.

If there are players A, B, C, D and player S is spectating, instead of infecting [A, B], then [C, D], then [A, B], one of the players, for example, A will always be chosen to become initial zombie.

> If people leave the game and rejoin the game from spectators, they will be zombie next round.
> Nothing wrong with that.

The steps do not mention people reconnecting

**Comment by teoman002** [comment]
great explanation!

I think the infected chooser was written for only one initial infected.
If someone wants to rewrite the mod.cpp, we can fix this issue.

**Comment by teoman002** [comment]
@bretonium @yavl 

What is unfair infection and why is it important? 
https://github.com/yavl/teeworlds-infclassR/blob/02043bf899c75659990e552ede9b0e796a55ce60/src/game/server/gamemodes/mod.cpp#L215

**Comment by bretonium** [comment]
I am reopening the bug because the fix was reverted

**Comment by bretonium** [comment]
```
diff --git a/src/game/server/gamemodes/mod.cpp b/src/game/server/gamemodes/mod.cpp
index e393405..9546ec8 100644
--- a/src/game/server/gamemodes/mod.cpp
+++ b/src/game/server/gamemodes/mod.cpp
@@ -219,9 +219,19 @@ void CGameControllerMOD::Tick()
                        }
                        
                        int NumNeededInfection = NumFirstInfected;
-                       
+
                        while(NumInfected < NumNeededInfection)
                        {
+                               // before infecting those who play, mark spectators as
+                               // already infected. It will prevent issue causing a
+                               // player getting infected several times in a row
+                               CPlayerIterator<PLAYERITER_SPECTATORS> IterSpec(GameServer()->m_apPlayers);
+                               while(IterSpec.Next())
+                               {
+                                       IterSpec.Player()->SetClass(PLAYERCLASS_NONE);
+                                       Server()->InfecteClient(IterSpec.ClientID());
+                               }
+
                                float InfectionProb = 1.0/static_cast<float>(NumHumans);
                                float random = random_float();
```
I came up with the following patch on my server

**Comment by teoman002** [comment]
please test what happens when you rejoin the game as spectator. Normally you should get infected.

My assumption is that If a client is tagged with "m_WasInfected" which is a consequence of InfecteClient(), then this client can't get infected the next round.
Do we want that spectators can't get infected after they rejoin the game?

**Comment by teoman002** [comment]
ok your code contains a new bug, you just have to infect the character, not the client!

**Comment by bretonium** [comment]
>  Do we want that spectators can't get infected after they rejoin the game?

This is a bug, yes. I think this bug is "better" than one client always getting infected.

> ok your code contains a new bug, you just have to infect the character, not the client!

I don't understand. What is the consequence of the bug?

**Comment by teoman002** [comment]
I will improve the initial infected chooser by skipping spectators Altogether. Spectators should have no influence on the game.

**Comment by bretonium** [comment]
#140 made things much worse. In a 1vs1 game 1 player always becomes zombie. To illustrate, if there are players A and B, then initial infected sequence will look like this: A, A, A, A, A, ... . #140 should be reverted as soon as possible.

**Comment by teoman002** [comment]
I make a pull request next time, if I think it works. Then I need your help with testing.

At first we were struck in the loop because I removed the unfair infection.
Now the unfair infection is called every single time which ignore ClientInfectedBefore, but not only that, it also generates random numbers which always choose the first zombie.

**Comment by bretonium** [comment]
Here is a great example of current infection system. Note that nobody joined or left the game.
![Screenshot_20190328_161009](https://user-images.githubusercontent.com/1087672/55169182-a18ded00-5174-11e9-8ad2-69f3cfab3c03.png)

7 people played and 3 were spectating. **astral@fedora got infected 3 out of 5 times**. Camperbob - 2 / 5. Suifiaw - 2 / 5. Hallo - 2 / 5. Prototype - 1 / 5. Why 2 other players never were infected is a mystery. 

One of the players, who was never infected in that round, had id 1 and played for 4 rounds in the next map, and was never infected again.

This bug is major and discourages people who get infected out of order to play.

**Comment by teoman002** [comment]
Thanks for further details.
I think I need some help from @yavl 
@bretonium do you think that if spectators have nothing to do with the infection process anymore, that this will be fixed?
I think the unfair infection random chooser is broken and does not generate proper random numbers, so that part has to be rewritten as well.
