### ISSUE TITLE
Humans get stuck after taxi

### ISSUE THREAD

**Issue by bretonium** [yavl/teeworlds-infclassR#128]
Steps to reproduce:
1. 2 humans go into taxi mode
2. Human-driver comes close to any ceiling so that passengers are inside the wall
3. Human-driver dies via /kill or somehow else

Expected: humans-passengers get pushed out of the wall
Observed: passengers are stuck in the wall

This is reproducible on all servers

**Comment by bretonium** [comment]
![Screenshot_20190314_191522](https://user-images.githubusercontent.com/1087672/54381306-b7d47d00-468d-11e9-9514-1edc0789f3a8.png)
Here `honk` is not killable by boomer and is stuck in the wall

**Comment by teoman002** [comment]
I noticed that humans which disable taxi mode, glitch trough the wall till they find a tile that is air.
But if the driver dies, taxi mode seems not to be disabling itself, instead the position remains fixed.
@yavl 
My suggestion is to change these lines:
Taxi-Mode: 503da3b73e39aa9bec70cf36c25147406b6aa098

	if (m_Passenger && (m_Passenger->m_Jumped || m_HookProtected || m_Passenger->m_Infected || m_Infected)) {
		m_Passenger->m_IsPassenger = false;
		m_Passenger = nullptr;
	}

Add something like this:

	if (driver->IsZombie)
		m_Passenger->m_IsPassenger = false;
