### ISSUE TITLE
If there are 3 players, 1 should become zombie

### ISSUE THREAD

**Issue by bretonium** [yavl/teeworlds-infclassR#131]
Some time ago we introduced a change that 2 players out of 3 become initial infected. Practice shows that it is very boring to play zombie 66% of the time and people quit.

I basically suggest to revert #99

**Comment by teoman002** [comment]
Will be fixed with early game nerfing.
https://github.com/yavl/teeworlds-infclassR/pull/104

**Comment by teoman002** [comment]
@ResamVi how do you think about this issue?

**Comment by ResamVi** [comment]
Practice shows that it is very boring to play more zombie indeed but I say with this suggestion implemented it will be just boring the other way around: the zombie is bullied into submission, especially on big maps where there is a lot of walking involved before any action.

In my opinion 2 zombies are about equally equipped to handle a single human but two humans are a lot more equipped to handle a single zombie so maybe we can reconsider this with #104 implemented.
