### ISSUE TITLE
Passenger and driver switch places after hooking sometimes

### ISSUE THREAD

**Issue by bretonium** [yavl/teeworlds-infclassR#133]
Passenger and driver sometimes switch places after hook in taxi mode. I do not have exact steps to reproduce, but it happened to me twice with different people. I will post a comment if it happens again.

I think it started to happen after 22e6e8f2bd3d29982d22137e8bbf0a68fa23015a.

**Comment by teoman002** [comment]
couldn't be verified. Please reopen when it happens again!
