### ISSUE TITLE
Failback mode

### ISSUE THREAD

**Issue by teoman002** [yavl/teeworlds-infclassR#136]
For the future I suggest to run the master_dev server as long as no crash occur.
In case of a crash, the server loads git origin master, execute server_d and restarts the "fail back mode" which is the stable master.

The master_dev server can be called via vote.
A message appears that says that the "countdown 0 - development server starts now, please rejoin"

**Comment by yavl** [comment]
This is an unnecessary complication. One could always write a tiny launcher script on his own if he really needed something you proposed. Either crashes should not present on master. I think the 'Slightly modified infclass' thing is pretty much finished except some small issues, that means there will be no big changes that may cause server crashes etc.

Some gameplay changes are expected to be added for the \*next-gen\* teeworlds 0.7+ infclass with a cleaner, easier to add infclass-related stuff close-to-vanilla code with less traps in it. Though not sure, I expect that it would be fun to play on infclass with battle-royale like elements such as circle that gets smaller as the time goes on. It should also make few players gameplay fun.
