### ISSUE TITLE
Server went into 100% CPU usage mode

### ISSUE THREAD

**Issue by bretonium** [yavl/teeworlds-infclassR#139]
![Screenshot_20190322_230220](https://user-images.githubusercontent.com/1087672/54855515-eccc7980-4cf6-11e9-8282-64788e9383c9.png)
As you can see from the screenshot, server_sql_d process eats 95%+ of CPU time. It was happening for approximately 2 minutes, then i killed it so that my hoster doesn't yell at me. Usually this is an indication of an endless loop somewhere.

This happened at the moment when initial infection was supposed to happen. There were 2 players, round 3/5. Last log lines:

```
[5c955b04][game]: start round type='InfClassR' teamplay='0' id='1350490027'
[5c955b07][chat]: <chat>
[5c955b08][game]: choose_class player='<a player>' class='4'
[5c955b0c][chat]: <chat>
[5c955b0e][game]: choose_class player='breton' class='10'
```

**Comment by teoman002** [comment]
Only I made changes to the code.
I guess, the Server can't find the initial infected and stays in the loop. 
Better we revert my rewrite and I think a bit more about it.

**Comment by bretonium** [comment]
It happened again. The server was on commit 145c1054c6eb38006928aa53957fcca98f980032.

I have connected to the process with gdb and added a breakpoint on `src/game/server/gamemodes/mod.cpp`, line 221. It is infinite loop indeed, the breakpoint was hit multiple times.

**Comment by teoman002** [comment]
can you teach me the steps you used in gdb to investigate the bug?
who can you check a break point?

**Comment by bretonium** [comment]
Compile the server with server_debug or server_sql_debug. Launch the server. Find out process id by `echo $?` or by doing `ps aux | grep server_`. Then connect to the process using gdb: `gdb -p <pid>`. You will get connected to a running process and the process will get paused.

Set a breakpoint with `b src/game/server/gamemodes/mod.cpp:221` (you can also set a breakpoint on method call with `b SomeClass::SomeMethod` and there are many other useful ways). Then continue the process by entering `continue` or `c` in short. If the process encounters the breakpoint, it will get paused again. If this is a cycle, you can use `c` many times and the breakpoint will be hit every time.

They detach from the process with `q`.

**Comment by bretonium** [comment]
Also i usually run `where` to display the backtrace. `l` to print current source code line, `p <variable>` to print a variable. Varible can be complex, for example, `p this->some_element.member[3]`.

**Comment by teoman002** [comment]
I took the exit statement (unfair infection) from the original commit.
This won't happen anymore.
