### ISSUE TITLE
InfClass-like mod for Teeworlds 0.7.3+ discussion

### ISSUE THREAD

**Issue by yavl** [yavl/teeworlds-infclassR#156]
In my opinion, there is no point in making a 1:1 infclass port to 0.7+ teeworlds. Another infection mod with classes could be made instead, with much cleaner codebase without (possibly) any direct insertions into base tw code, making it both portable and easy to add new features. Some configurable parts could be scripted in e.g Lua instead of dealing with many predefined config variables (useful for server hosters). The gameplay should change as well.

I suggest it to be something like this:
All players spawn on the map, someone gets infected and the game starts. There will be two large circles from battle royale games, one circle (similar to merc bomb circle) shows current safe zone, and the second circle (made of lasers) shows how safe zone will look in next N seconds. Outside of the safe zone humans lose their hp, the time for -1hp lose gets smaller as the distance increases. After they survived the smallest circle, zombies stop respawning after death and humans should either find an exit (escape from infection) or kill all zombies (clean map from infection) in a limited time, like 15 seconds. Spawn zone for zombies can be dynamic, in other words zombies could spawn at N distance from circle's edge.

With circles implemented, 3-4 player rounds should be almost as fun as bigger ones, so I hope there will always be some people playing on a server. I want to read your opinions/suggestions.

**Comment by teoman002** [comment]
> much cleaner codebase without (possibly) any direct insertions into base tw code
with polymorphism and inheritance is probably your idea - this will make coding more difficult for c++ newbies, because they have to understand pure virtual and virtual classes, overloading, overwriting.

>  Lua instead of dealing with many predefined config variables
why do you don't like config vars?, how does scripting reduce the amount of config vars if that is your intention?

> With circles implemented, 3-4 player rounds should be almost as fun as bigger ones, so I hope there will always be some people playing on a server.
Sounds great.

First of all, how do you plan to write a kinda new mod with the problem of already incompatible code from InfClass. My knowledge of c++ advanced coding is limited and I don't think I have the time to make a complete rewrite of InfClass. I don't mind porting it though.

**Comment by teoman002** [comment]
Let's first gradually implement your mod idea. And if that works, we can port infection.

**Comment by teoman002** [comment]
outline:

**SafeZoneCircle class**
- safe zone outer circle like mercenary bomb
- shrink size with each tick
- define minimal radius
- define maximal radius
- calculate distance between zombie and center
- if (human distance is bigger than currentRadius) TakeDamage(1 hp/sec ..  );
- if (distance is far) increase TakeDamage(4 hp/sec)
```
if (currentRadius == minRadius)
{
	GameServer()-> m_endGame == true;
	this-> Reset(); //Destroy outer circle
}
```

**PredictionCircle (subclass of SafeZoneCircle):**
- looks like engineer laser (I prefer white dots)
- shrink size each tick
- if (InnercurrentRadius == minimalRadius) stop shrinking
- if (InnerCurrentRadius == outerCurrentRadius) this->Reset(); // destroy prediction circle

**mod.cpp**
- if (all zombies are dead && m_endGame) -> SpawnFlag()
- if (Flag collected && m_endGame) -> EndRound()
- create dynamic spawn depending on currentRadius

**Comment by yavl** [comment]
'cleaner code' is intended to make it easier for 'newbies', not to complicate.

> how does scripting reduce the amount of config vars if that is your intention?

I meant some things (such as Fun Rounds, for example) would better be scriptable thus modifiable without need of recompile / dealing with c++ code. It could be possible to init those global vars from script file.



> First of all, how do you plan to write a kinda new mod

It actually sounds pretty easy to do it. Infection is just skin changes on pick/death, kill conditions and given initial weapons and two circles. All this could be written in 1 day with enough inspiration/time. Some complicated classes (ghost, voodoo etc) could be added later, this repo will be used as reference. Not sure about that radial class picker menu though as I haven't looked at it.

I'm not a c++ expert either, but I am sure the new mod will be less confusing code-wise. I think I will write basic infection with classes these weeks. The gameplay should be thought out though, to not make another 0.7 mod with constant 0-player online

**Comment by teoman002** [comment]
>  Fun Rounds, for example) would better be scriptable thus modifiable without need of recompile / dealing with c++ code. 

@duralakun made a great improvement to the fun rounds. They can be started via rcon from text tiles, which are defined in the bin folder. You can also create fun rounds on the fly manually and then start them. At the end normal configuration is restored. I was not able to test it, but it sounds promising.

> I am sure the new mod will be less confusing code-wise. I think I will write basic infection with classes these weeks.

Do you want to code it with the help of infection 0.7? How is the code tested? I can help when I have some free time.

**Comment by AssassinTee** [comment]
As a side note:
If you want to update to 0.7.3, you will see, that a **new netmessage** appeared:

You can now send skinchanges with an own netmessage!

I already implemented a skinchanger method, that is working for older Clients < 0.7.3, too.
See https://github.com/AssassinTee/catch64 (gamecontext.cpp SendSkinChange)

Good Luck!
Assa

**Comment by yavl** [comment]
@AssassinTee thanks, the 0.7 version [is being developed](https://github.com/yavl/teeworlds-infcroya/tree/infcroya) already, not yet ready for contribution though, thus bad commit messages etc (will be squashed).

**Comment by yavl** [comment]
[teeworlds-infcroya](https://github.com/yavl/teeworlds-infcroya)
