### ISSUE TITLE
Gather some stats

### ISSUE THREAD

**Issue by AssassinTee** [yavl/teeworlds-infclassR#167]
In order to tweak parameters, you should start gathering some stats:

- wins/loses per map
- wins/loses per playernumber
- kills per weapon
- kills per class
- survival time per class
- i guess some more

I think this mod needs some balance and gathering stats indicates what to buff/debuff.
For example in 0.7 the zombie hookdamage seems much to high and the soldier class is very strong, while a medic feels useless

**Comment by yavl** [comment]
@ResamVi already did some work on ingame- and web-based stats for 0.6 version (should also work on 0.7 without any changes). See [infclass-stats](https://github.com/ResamVi/infclass-stats) and [infclass-stats.tk](http://infclass-stats.tk). It connects to teeworlds econ, and then parses console output. With those extra console messages added, stats should work for 0.7 version as well.
