### ISSUE TITLE
bam : error : a build step faild

### ISSUE THREAD

**Issue by SeniorSpirit** [yavl/teeworlds-infclassR#169]
when i do 
bam server_debug

i got 
bam : error : a build step faild

error

**Comment by teoman002** [comment]
Unfortunately that is not enough information.
Please provide the entire build log from start to the error.

**Comment by SeniorSpirit** [comment]
https://mega.nz/#!Abh2kK4L

its video from starto to end

**Comment by SeniorSpirit** [comment]
can someone compile it and send for me? tnx

**Comment by teoman002** [comment]
Install mingw and add its bin folder to environment variables. This is a c++ compiler for windows.
[MinGW](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe/download)
[Environment variables](https://www.rose-hulman.edu/class/csse/resources/MinGW/installation.htm)

**Comment by SeniorSpirit** [comment]
tnx i add mingw to environment variables and it fixed

**Comment by SeniorSpirit** [comment]
now i got server_d stopped working when open file server_d.exe

**Comment by teoman002** [comment]
open the exe through a terminal window, it will show you the error message.
Please tell me what it says.
You might need an autoexec.conf to set server parameters

**Comment by SeniorSpirit** [comment]
i run many servers and its first time i got this erors , when i open through terminal no eror show to me

**Comment by yavl** [comment]
maybe wrong DLLs were copied? Try to copy .dll files from [teeworlds-infclassr/other/icu/gcc/lib32](https://github.com/yavl/teeworlds-infclassR/tree/master/other/icu/gcc/lib32) next to server_d.exe.

I could send you binaries if it still fails.

**Comment by SeniorSpirit** [comment]
it dosent work

**Comment by yavl** [comment]
@SeniorSpirit windows binaries (32bits) https://mega.nz/#!apc3GYKA

**Comment by SeniorSpirit** [comment]
tnx it works now :D
