### ISSUE TITLE
Automaticly select language depending on the IP country

### ISSUE THREAD

**Issue by NewRedsquare** [yavl/teeworlds-infclassR#172]
I think that's not hard because we already have the GeoLite DB...

**Comment by yavl** [comment]
It is already implemented, player is prompted to switch language according to his country flag. Country flag is [set by server](https://github.com/yavl/teeworlds-infclassR/blob/master/src/game/server/gamecontext.cpp#L2069) according to player's ip address, when compiled with geolocation.

**Comment by NewRedsquare** [comment]
i mean, there are too much stuff displayed when a player connects : if the language can be changed WITHOUT being asked to, it can be nice !
