### ISSUE TITLE
weird white line on k9f_small

### ISSUE THREAD

**Issue by bretonium** [yavl/teeworlds-infclassR#176]
![Screenshot_20200510_140354](https://user-images.githubusercontent.com/1087672/81498806-37c49a00-92c7-11ea-90c3-af39565ab19b.png)
No steps to reproduce, just join the map. Notice the light line @ bottom

**Comment by bretonium** [comment]
![Screenshot_20200510_142002](https://user-images.githubusercontent.com/1087672/81499103-575cc200-92c9-11ea-8eb7-f72f728bd3a2.png)

This is a screenshot of my settings

**Comment by teoman002** [comment]
![entire_map](https://user-images.githubusercontent.com/1367821/81499219-62a7f180-92b9-11ea-88fa-28c8929890a7.png)

**Comment by teoman002** [comment]
![fixed](https://user-images.githubusercontent.com/1367821/81553801-36ea4180-9375-11ea-91a4-15b46fc54c19.png)

**Comment by bretonium** [comment]
The line is there again
![Screenshot_20200516_125705](https://user-images.githubusercontent.com/1087672/82118041-ce380600-9774-11ea-866e-0ccd20432fdc.png)

**Comment by teoman002** [comment]
![screenshot](https://user-images.githubusercontent.com/1367821/82129730-512c8100-97b4-11ea-9044-1d89b048f230.png)

Not reproducible with my ddnet config, I uploaded another fix, maybe your error was fixed too.
