### ISSUE TITLE
Delete stale branches too reduce occupied hdd space of repo

### ISSUE THREAD

**Issue by teoman002** [yavl/teeworlds-infclassR#33]
See title.

**Comment by bretonium** [comment]
Branches do not take much space. By deleting them you will free up a couple of kilobytes of space. But it is not enough to delete them - you need to run a cleaning command on your computer locally after that to really get these 2kb back.

Here is what takes most space:
```
12M     objs
23M     bin
188M    other
```

What takes a lot of space is binary files in `/other`. I don't understand what those binary files do. Deleting them from the repo and then from history could really get us some space.

But frankly, i don't think that it's worth it. You clone it one time and every pull and push just fetch differences, which is a couple of hunderd of bytes. We'll waste more time than save.
