### ISSUE TITLE
Few players - unbalanced gameplay

### ISSUE THREAD

**Issue by duralakun** [yavl/teeworlds-infclassR#48]
Problem:
It is difficult to jump start a server. When there are only few players playing the server can die easily.
If there are only 3 players playing - 2 zombies, 1 merc, it will be much easier for the merc to escape. Which will make it annoying to play as zombie. The same goes for hero. It is much easier for the hero to find flags when there are only few players on. Playing with only few players is very unbalanced and not fun which leads to players leaving and making the problem worse.

Solution 1:
Nerf certain human classes depending on how many players are online. For example give heroes only a grenade launcher when there are at least 6 players. Reduce reload speed of merc pistol. Let scientists only have 1 mine and remove its teleporter. Let ninja only have 1 zap before touching the ground again. And maybe more....

Solution 2:
Buff the movement speed of all zombies depending on how many players are online.

Solution 3:
Give each map a minimum player number. For example infc_warehouse and hardcore pit could have a very low min player number (of 0) while infc_newdust and spacelab could have higher one. If the next map has a higher player number than online players it will skip the map and search for a map with lower min player number.

**Comment by teoman002** [comment]
solution 1 sounds good, I want to introduce nerf_factors that decrease damage of classes.

**Comment by teoman002** [comment]
Solution 1

Introduce new config vars called 
- g.Config.m_Inf_NerfFactorLevel1 
- g.Config.m_Inf_NerfFactorLevel2

They change the parameters of human classes

The affected parameters will be:
- medic shotgun blow back + damage
- hero shotgun damage
- scientist mine damage
- looper laser damage
- engineer wall duration
- soldier bomb damage
- sniper damage

Nerf factors will be activated on the basis of online players
level 1 = 40 (%), for max 3 players
level 2 = 70 (%) for max 5 players

Nerf factors will be deactivated after  >5 players
tweaking factor will be 100 (%) then

**Comment by bretonium** [comment]
Weakening humans is a good thing when there are not many players, indeed.

However, infclass with many players is different from infclass with few players. With many players, there are roles - defense, support, medic, hero. Zombies win by finding weak parts in that system. Individual players do not survive against zombies. Yes, they can still have fun, but they definitely get infected and lose. Personal skill does not help you if the rest of your team fails.

With few players there are no roles. Everybody plays individually and has fun. Personal skill becomes the main driver of the game. The game basically becomes dm/tdm. And i think we should embrace that by removing abilities that make humans tactically more powerful than zombies:

- flying of mercenary
- insta-kill of engineering walls (maybe they could deal N damage?)
- looper walls
- insta-kill of scientist's mine (maybe they could deal half of normal damage?)
- hero flags
- 3 scientist's mines (maybe leave 1?)
- 2 ninja katana-jumps (1 is enough)

We should not make zombies' life too easy though. Lets not forget that they still can heal each other or that they have full armor when there is only 1 zombie.

The cut-off limit should be 6 players. 6 - nerfed game, 7 - non-nerfed.

**Comment by bretonium** [comment]
P.S. medic is fine as is, i think :3

**Comment by duralakun** [comment]
Solution 4:
Make an alternative gamemode that will be activated when there are less than 4 people on. In this gamemode there will be no start zombies, instead humans will fight against ai. This could be bots that look like zombies and try to hammer you, or maybe flying rotating triangles that shoot at you. This way the game could be fun even if there is only 1 player on. But of course this would be hard to program and take a lot of time. Just wanted to put the idea here.

**Comment by duralakun** [comment]
I think solution 4 is the best, if implemented correctly.
There could be a config var that defines when bots should join. (how many people are on)
For example it could be set to 1. Than only when 1 player is on bots will join and we would have a singleplayer mode. But of course implementing it might be very difficult.
This might help: https://github.com/LordSk/teeworlds/tree/mod/zomb (it is a zombie mod with bots)

**Comment by teoman002** [comment]
Please read #101 first.

**Comment by teoman002** [comment]
**Todo:**
- parametrise merc bomb
- parametrise hero-flag
- fix engineer wall damage mechanic -> free points for dealt damage
- find a formula for NerfFactor

**Comment by yavl** [comment]
Solution 4: (just an idea)
When there are few players, 'Hide and seek' mode is activated - humans spawn as basic class with pistol-only and with 1hp. Zombies will be too powerful then, so if it's possible those pistol-only 1hp humans should behave like Ghost but against zombies.

**Comment by duralakun** [comment]
@yavl you have to call it Solution 5 i already made 4 :P
I am not sure if it would be a good game mode for few players. But I do think it could be a nice feature if it is similar to a fun round. So for example, you type "start_hideandseek_round" in the console and it will start a hide and seek round.

**Comment by teoman002** [comment]
With regard to solution 4, I would suggest to implement solutions, which increase the motivation to work together. When player join the game and are nearly alone it is very boring, finding another player on a big map isn't helpful either.

Solution 5:
My suggestion would be zabys from Zomb-mod. However, the mechanic is very hard to understand and would be a copy from another repo. I think it would not be fair to the creators of zomb-mod.

**Comment by bretonium** [comment]
Initially-infecting 2 humans in a 3-people game looks bad. It quickly becomes boring to be zombie 2/3 of the time and people quit

**Comment by teoman002** [comment]
Yea if nerfing is introduced there is no reason to increase initial infected count.

**Comment by Kaffeine** [comment]
Changing the rules at game time is a bad idea. (If a player put a laser wall then they expect that nobody can go thought). I would suggest to *disable* some classes (e.g. `hero`  if there are just a few players.)

An option to change own zombie class would help a lot.

**Comment by teoman002** [comment]
Your suggestion about wall is understandable. I probably revert the "parametrize engineer wall" commit.
