### ISSUE TITLE
scatter-flash-grenade does not explode if zombie is hit

### ISSUE THREAD

**Issue by teoman002** [yavl/teeworlds-infclassR#58]
scatter-grenade.cpp has to be modified.
mercenary scatter-grenade needs to be independent from this fix by using the m_isflashgrenade variable.

- TODO: correct trajectory estimation (the hard part) and explode on human impact.

**Comment by duralakun** [comment]
This might help:
https://github.com/yavl/teeworlds-infclassR/blob/master/src/game/server/entities/projectile.cpp#L80
in projectile.cpp grenade collisions will be detected
