### ISSUE TITLE
the /random command

### ISSUE THREAD

**Issue by duralakun** [yavl/teeworlds-infclassR#63]
New feature suggestion:
At the start of a round when you choose your class you can type /random to get a random class. (or click the button)
If you dont like it, you can type /random one more time to get another class. But the second time you wont get the extra armor and start with no armor.

**Comment by ResamVi** [comment]
There is /alwaysrandom but you see absolutely no use of that anyway. If you see somebody with a class way before anybody else has picked you know he has it activated. But what makes you think that will find any use?

**Comment by duralakun** [comment]
The important part is that people can do /random one more time after they got a random class. There might be a class someone doesnt want to play but still wants to play with any other class, this way he can avoid that specific class. (the disadvantage of the second random class is that you get no armor)

**Comment by ResamVi** [comment]
You should ask random people around if they even noticed that you'll get armor if you pick random. I didn't until I saw the code.

This still sounds so backwards. People pick random and then they don't actually want it to be random. So why not pick something explicity?

**Comment by ResamVi** [comment]
What about dislike of multiple classes?
I don't like sniper nor mercenary. I choose /random once and get sniper and on second try I got mercenary. Now I've got no bonus and no preferred class.

**Comment by duralakun** [comment]
ResamVi i dont see how this feature would harm the game in any way. Some people might like it and use it, most will probably not use it and dont care about it.

**Comment by teoman002** [comment]
If you have the time to code it, I don't mind, Breton can deactivate it with config var.
