### ISSUE TITLE
Suggestion: Changing Ninja

### ISSUE THREAD

**Issue by duralakun** [yavl/teeworlds-infclassR#65]
I am thinking about this since some time now:
- Remove target system - instead every kill gives 1 point, an assist gives half a point
- For every point the ninja gains 1 damage upgrade + 1 health (not more than max health)
- For every 3 points or so ninja gains a speed buff (when he attacks / slashes)
- For every 5 points or so ninja gains 1 extra grenade ammo
- Ninja starts with only 1 slash in mid air and gains another one after 3 points or so
- Ninja is immortal while slashing (so he can slash boomers without stunning them first)
- Ninja can explode stun grenades mid air (like merc grenades)
- Remove pistol (no longer needed, makes it easier for noobs to switch between the 2 main weapons)
- Ninja starts with 7 damage or so (this would mean he needs to kill 3 zombies first before being able to instant kill them / if they have no armor)

The exact numbers can be changed / need to be balanced. 
What do you think?

**Comment by teoman002** [comment]
how is the status of this suggestion?
I don't play ninja, so I can't tell if it is good or not.
But the pistol is useful for insta slash kills. I don't think it is good to remove it, even if slash gets stronger.
