### ISSUE TITLE
Infinite flying when boomed with collision off

### ISSUE THREAD

**Issue by bretonium** [yavl/teeworlds-infclassR#7]
Steps to reporoduce:
1. 2 zombies, 1 of them is boomer
2. Both turn off hook protection (and collisions)
3. Both stand in the same position - for example, in some corner
4. Boomer explodes

After this the second zombie flies away somewhere and never dies

**Comment by bretonium** [comment]
Some debugging can be performed if you press Ctrl + Shift + D in the client

**Comment by bretonium** [comment]
*turn hook protection on (and collisions off)

**Comment by yavl** [comment]
^ this one was fake fix
