### ISSUE TITLE
Suggestion: Tarzan-mode for humans or bats or both

### ISSUE THREAD

**Issue by yavl** [yavl/teeworlds-infclassR#78]
A more natural and less clunky taxi mode. Let hook-protected humans infinitely hook non hook-protected humans without affecting them.

Example for humans:
16 players on the server, spacious map (normandie, damascus, newdust) is being played, Mercenary is not hook-protected and 3 other tees are hook protected. Those 3 tees hook mercenary and then mercenary starts flying with a tail of 3 tees.

Example for bats:
Bat-only feature for quick infected forces' transportation on large maps. Same behaviour, unlimited number of zombies hook Bat and fly with him. If zombs won't stop holding hook button, Bat could throw down zombies at any time by enabling hook protection.

At a distance smaller than minimum, hook should behave like spider's hook on web mode.

**Comment by teoman002** [comment]
Tarzan mode for humans, outline:

- condition: driver is not hook protected
- condition: guests are hook protected
- condition: driver is hooked
- behaviour: enable spider mode for guest, hook has a maximal length, if hook get's too long, the distance between driver and guests is held constant, guests position changes accordingly.

- exit condition: driver is hook protected
- behaviour: disable spider mode from guest
- behaviour: remove hook

**Comment by teoman002** [comment]
@yavl can you help me with the coding of 1 2 3 5 ?
I do 4) 6)

**Comment by teoman002** [comment]
look in character.cpp line 1933
player.cpp line 208

**Comment by yavl** [comment]
@teoman002 yeah, but i don't know how to deal with client hook predictions, removing it for Bats when hooked by zombies but not humans

**Comment by teoman002** [comment]
Why do you need to disable client hook predictions?

if GetPlayer->IsZombie() {DisablePredictions}
if GetPlayer->IsHuman() continue;
