### ISSUE TITLE
Merc bombs killing humans

### ISSUE THREAD

**Issue by duralakun** [yavl/teeworlds-infclassR#84]
Because of the strong explosion of merc bombs it is possible to kill humans with it in certain maps.
You place it next to spikes or void and wait until a human comes by and then explode it so it will push the human into the spikes or void.
Possible solutions i can think of:
- Dont allow merc bombs to influence the movement of other humans except the owner of the bomb
- Dont allow mercs to explode their own bombs
- Replace merc bombs with turrets

(i think solution 1 is the best)

**Comment by teoman002** [comment]
merc bombs shouldn't affect humans, there is no reason for it. -> bug
