### ISSUE TITLE
Fun Rounds breaking random pick feature

### ISSUE THREAD

**Issue by duralakun** [yavl/teeworlds-infclassR#86]
I wanted to code it so that the server remembers the last 3 classes a human picked and do not give it to him again if he chooses random. Then i found that this function already exists:
https://github.com/yavl/teeworlds-infclassR/blob/master/src/game/server/gamemodes/mod.cpp#L839
But is commented out because apparently it breaks fun rounds. This is not a good solution. Instead please make a check if there is currently a fun round going on or something like this.

**Comment by yavl** [comment]
Or just remove fun rounds

**Comment by duralakun** [comment]
thanks
