### ISSUE TITLE
Hero indicator idea

### ISSUE THREAD

**Issue by bretonium** [yavl/teeworlds-infclassR#95]
Hero indicator shows where the flag is. I disabled it on my server for 2 reasons:

1. Several people (me included) thought that it made playing with hero boring. No need to search the flag, just follow the white dot!
2. I personally think it made heroes too powerful on some maps and with few zombies.

However, on some maps it might be frustrating to search for the flag and not to find it for a long time. For example, on huge infc_towers.

Lets show it in stages.  Each stage takes 10 seconds. Stage 0 starts right after the flag appears.
Stage 0: no indicator
Stage 1: indicator is visible 1 time for 1 second
Stage 2: indicator is visible 2 times, each 1 second
Stage 3: indicator is visible 3 times, each 1 second
Stage 4: _you guessed it_

**Comment by teoman002** [comment]
No objections,
it can be done in indicator.cpp
We can use the constructor, tick() and snap() for that.
It takes several static counters or instance variables.

**Comment by duralakun** [comment]
I like this idea.
And or it could also be so that the indicator will only be visible if the hero stands still.
Stage 0: no indicator
Stage 1: if the hero stays still for 3 sec the indicator will appear
Stage 2: if the hero stays still for 2 sec
......
Stage X: As soon as the hero doesnt move the indicator will be shown

**Comment by teoman002** [comment]
I prefer, stays still for X seconds.

**Comment by bretonium** [comment]
> And or it could also be so that the indicator will only be visible if the hero stands still and disappear again as soon as he moves.
> Stage 0: no indicator
> Stage 1: if the hero stays still for 3 sec the indicator will appear
> Stage 2: if the hero stays still for 2 sec
> ......
> Stage Z: As soon as the hero doesnt move the indicator will be shown

I like this idea more than mine

> Or without stages and the indicator will only show after the hero stays still for X seconds.
> X is a config var, we could agree on a default value.

That would be a good first step

**Comment by duralakun** [comment]
Ok cool, i think there is already a timer that is used to move people to spectators if they are inactive. We might be able to use the same counter to lookup how long a hero has not moved.
