### ISSUE TITLE
We need more config vars

### ISSUE THREAD

**Issue by duralakun** [yavl/teeworlds-infclassR#96]
Config vars are awesome. They make the server more flexible and give them extra features.
The possibilities are endless. 
For example we could create fun rounds by using config vars.
Someone could create a cfg file that gets executed when people vote for it.
This is already possible. What is not possible i think is to automatically reset it after the fun round ended.
But the idea is that the more config vars we have the more we can do with it.

**Comment by teoman002** [comment]
We can vote to make changes to config vars and reverse it by loading the complementary commands from another file.

**Comment by duralakun** [comment]
Yes, the only problem is an admin would need to load the complementary commands or people would need to the reverse the changes. But maybe we can create a config var that as soon as it is set, the server will remember all up coming changes to config vars and than automatically reverse them at the end of a round.
Fun round idea with cfg vars:
Looper vs Boomers
reverse gravity effect of looper slow mo, so that boomers fly up
make lase rifle do less damage therefore increase slow mo duration

**Comment by duralakun** [comment]
Also breton had the idea of making it so you can add config vars to mapinfo files.
So you could create a map with specifc config vars and as soon as the server loads it it will execute the config vars.
I thought about making maybe 2 names for it, startcfg, and endcfg, so inside the mapinfo file you could write it like this:
startcfg "here your config command that will be executed when the map gets loaded"
startcfg "here your config command that will be executed when the map gets loaded"
startcfg "here your config command that will be executed when the map gets loaded"
endcfg "here your config command that will be executed when the map ends"

**Comment by teoman002** [comment]
You try to access config vars from mapinfo files?
Yea why not, good idea.
